---
title: "Thoughts on poverty"
description: |
  A short description of the post.
author:
  - name: Cody Tuttle
    url: https://codyrtuttle.netlify.app/
date: 2022-09-13
output:
  distill::distill_article:
    self_contained: false
categories:
  - no code
  - poverty
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Hey folks - I don't have much time to post right now, but in the spirit of posting more frequently and being less of a perfectionist, I'm going to write for 15 minutes about my current musings and thoughts on poverty. The new poverty numbers from the Census Bureau came out today, and they've got me somewhere in between my head and my heart reflecting on the dynamics of poverty - the intellectual and scholarly understanding, the political economy and societal optics, the lived reality and experience of people in poverty. With all of this, I'm just going to take 15 minutes and just get my thoughts down in writing. Like I alluded to, this is probably going to be something in between intellectual/academic musings and personal/emotional reflection. But whatever it ends up actually being, it's the honest and raw thoughts that are swirling in my brain right now. I hope to find the time soon to do a little more digging into these reflections, both from a conceptual and philosophical perspective, but also the data and research. 

Here it goes:

***

I will start out with an obvious but I think important qualification on all of these thoughts: I am a very privileged white male living in an upper-middle class neighborhood with a poverty rate of next to nothing. I have never experienced real poverty aside from being a broke college student. I didn't experience poverty growing up as a kid, nor have I experienced poverty as an adult. I live in a decently large city, so I see poverty around me fairly frequently, but I am not residentially- or socially-proximal to poverty in the way that I'm reflecting on now. 

The new poverty numbers have me considering how complex and dynamic poverty truly is. At a very top line, without actually reading into the details just yet, the Census Bureau released the poverty statistics for 2021, and poverty by most conceptions is down considerably from 2020, especially child poverty. This is a true dynamic, and it's a good thing, full stop. But the official poverty numbers, whether in the form of the official poverty measure or the supplemental poverty measure, do not even come close to really capturing the experience of people living in financial and material deprivation. 

Official statistics, whether absolute (like the official poverty measure) or relative (like the supplemental poverty measure) are based on hard thresholds and cutoffs for who falls into the "poverty" category and who does not, because they have to be. But what these cutoffs miss is the experience of people who are just beyond that bright line - people who have income a little higher than whatever threshold is being used, but are actually no better off than the folks just below it. So much policy, so many benefits, so much scholarship and research, is based on these arbitrary lines, and it leaves out the real experience of so many people. So many families are denied benefits because they have income a few dollars higher than the poverty criteria being used, benefits that the new numbers and years of evidence show actually help families improve their circumstances and life prospects. 

Another thing is that these numbers, especially the official poverty measure, are based on calculations taken at one point during the year. They're a sampling of folks who were above and below the cutoff at one point during the year. But this completely missed the inherent dynamic nature of poverty. Lots of research shows that it's just really really easy to fall into poverty. Most families and individuals are just one emergency or accident away from slipping into devastating financial circumstances that could completely redefine their entire life trajectory. ***My*** family is just one emergency away from this. 

And yet. Something that the new numbers also miss is that communities of color and other historically and currently marginalized groups are *so* much more likely to experience poverty than white folks. The truth is that my family and I are most likely able to weather an emergency or shock a lot more easily than another family that looks just like us but are Black, simply because of the societal and generational privilege we are privy to. 

Poverty is complex and dynamic. There are so many ways of knowing that we need to tap into - not just the official (or supplemental) statistics, but deeper quantitative analysis that looks at distributions and timing, and most importantly, real qualitative lived experience of folks in and near poverty. 




