---
title: "Quick updates and musings"
description: |
  A short description of the post.
author:
  - name: Cody Tuttle
    url: https://codyrtuttle.netlify.app/
date: 2022-08-06
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I know it's been ten thousand years since I posted (ok not really that long, but still pretty long), but I wanted to get back on here and renew my intentions of actually posting on here semi-regularly. The last year or so has been decently bonkers with my daughter, but I really do want to make time for this. Blogging and data exploration is something that really has brought me a lot of joy. 

I guess the reason that I'm writing this now (and hopefully pushing it live before Liv wakes up from her nap) is because I've been seeing SO MUCH about the new Quarto platform from RStudio (soon to be Posit?). I went down a rabbit hole for a few hours this week of trying to figure out converting my website from distill to the new Quarto system or creating a new separate "musings" style blog using Quarto. But at the end of the day I realized that there is plenty of time for that, and I don't need to rush into it now - the more helpful and productive practice is actually just making use of the blog I have now. 

So here we are, getting back into it. 

This is my first new post (albeit not a real post), and from here on out, I'd like to mainly do small pieces that don't necessarily have to be super well-thought out or composed. The perfectionism is what keeps me from posting so much of the time, and I want to start to free myself from that. Occasionally I'm sure I'll do longer deep dives and walk-throughs, but for now I just want to continue to take the chance to write, to explore data that interests me without the self-expectations of it being perfectly insightful. Consistency and progress are my goals. 

I'm committing here now that the next post I do will be soon, and it will be just a small interactive table showing NYT best sellers. TidyTuesday released a data set on NYT best seller lists, and I played around with it a few months ago. I already have the code and and the table basically ready, so now I just need to put it in post form and publish it. 

But I wanted to do this post first, as a way to re-commit myself to this. We'll see where it takes me, and I sincerely appreciate the at-most five people who will read this and follow along.

Cheers until next time!


