---
title: "A true welcome"
description: |
  Why I'm here
author:
  - name: Cody Tuttle
    url: https://codyrtuttle.netlify.app/
date: 12-07-2020
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Greetings, esteemed guest! 

I'm so glad you made it to my site. Whether you've known me for a long time and you're only here because I asked you to check out my site, or we've never met and you stumbled across this somehow, thanks for being here. I know that there are a lot of other places on the internet you could be and a lot of other things you could be doing with your time, so that you've chosen to spend a few minutes here is something I don't take lightly. Thanks.

I wanted to take a few minutes to jot down some thoughts about why I started this and what I'm doing here. As you probably figured out by now, this is my site where I blog about data and public policy. I'm a research scientist and policy analyst by trade, and I love working with data - this is my creative outlet to explore the areas that I'm passionate about and get better at my craft. Exploring new data sets about topics that I care about is really exciting to me, because I get to both learn a lot and help people out in the process. One of the ways that I learn best is by following along as people show me how to do something, and that applies to data science especially. I love finding new data and R blogs to follow and explore, particularly when they're at a skill level that's close to mine or just slightly more advanced. Hopefully this site can be that kind of a resource to people who are interested in improving their data tool box. 

### Old site

This site is really a reincarnation of a [previous blog](https://crtuttle.weebly.com/) that I started back in the summer of 2019. I was on break from my MPP program at the time, only doing an internship and no classes, and I wanted to do something productive with my down time that would help my job prospects once I graduated, either in terms of actual experience and skill-sharpening or just a portfolio to point to. Over the course of the summer I really started to enjoy the process of exploring new data sets and writing about both my process of analaysis and visualization and also the insights and thoughts I was pulling from the analysis. I did circa 10 posts over the course of around three months, most of them going through new data sets in R, but also some posts about Tableau public dashboards I'd made or with my thoughts about a particular policy area that I'd been thinking about a lot. After school started back up again in the fall I wasn't able to keep it up, but I did do a few more posts during the winter break between fall and spring semesters. Since I graduated in May 2020, I've been meaning to pick it back up again, but time the last six months has gotten away from me, with starting a new full-time job, buying a house, afinding out that my wife and I are expecting our first child, and general COVID craziness. I also knew that I wanted to create a new site, which would take some planning and investment on top of the time to actually write new posts. My old site, while functional and serviceable, didn't look that great and it was not at all integrated with the rest of the writing and analysis workflow I've developed in RStudio and R Markdown. 

### New site!!!

Enter this new site! After things At various points over the last year, I've seen posts and resources on various ways to start blogs using R packages, like `blogdown` and `distill`, but I wasn't able to really sit down and start thinking about it until now. I tried starting a site using `blogdown` and Hugo, and while I'm sure it's a great tool that works for a lot of folks, I wasn't able to get it to work. One of the other posts that I'd seen, though, was [this one](https://themockup.netlify.app/posts/2020-08-01-building-a-blog-with-distill/) from Tom Mock about starting a blog using `distill` and Netlify - it worked a lot more seamlessly for me than did the `blogdown` approach, and now we find ourselves here!

Mostly, I see this new site as a better-looking and easier-to-work-with continuation of the old site in terms of content and purpose. I'm really excited to get back to exploring new data sets and getting better at my analysis and visualization skills, so I imagine that will by main focus for the first stage in this new site. I'd also like to explore new territory with this blog, though. There are a few domains that I've been really itching to get into, like machine learning, interacative web graphics using d3 and JavaScript, and I'd love to use this as a way to explore them. I'd also like to create more Shiny web apps and blog about them here. Currently I have one Shiny app that I made for a class, and I've been meaning to build more - it's a super fun platform. 

Right now I'm thinking that the first new post that I do here will be analyzing my Strava app running data. I figured out how to download it a few weeks ago and I've had a good time playing around with it. I'm also debating building a Shiny app for it, but that remains to be seen. Other than that, I'm wide open to new data sets and topics. 

Well, folks, that's all for now. If you want to learn more about me, check out the "About" page on the site. Thanks for stopping by and taking the time to read this - I'm looking forwrad to posting more soon!


